### ISSUE TITLE
setting baseUrl doesn't work

### ISSUE THREAD

**Issue by weirdo21371480** [wvacalm/chatPDF#7]
const embeddings = new OpenAIEmbeddings({
      openAIApiKey: process.env.OPEN_API_KEY, // In Node.js defaults to process.env.OPENAI_API_KEY
      batchSize: 512, // Default value if omitted is 512. Max is 2048
      configuration: {
        baseURL: "https://api.132999.xyz/v1/",
      },
    });
    
    const llm = new OpenAI({
        modelName: "gpt-3.5-turbo-instruct",
        openAIApiKey:  process.env.OPEN_API_KEY,
        configuration: {
          baseURL: "https://api.132999.xyz/v1/",
        },
        temperature: 0.5
      });
      
      I set the baseUrl ,but it doen;t work.

**Comment by walicar** [comment]
It seems you are incorrectly passing in the configuration object, you may want to refer to [this thread](https://github.com/langchain-ai/langchainjs/issues/388#issuecomment-1490421309). 

Closing this thread as this topic pertains to Langchain rather than ChatPDF itself, futhermore issues should be brought to Langchain's github repo.
